modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_author}"
description = '''
Critters and Companions is a vanilla-style creature mod which fills the overworld with new animals.
'''
updateJSONURL = 'https://api.modrinth.com/updates/critters-and-companions/forge_updates.json'

[[dependencies.${mod_id}]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
